# -*- coding: utf-8 -*-
"""등굣길.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ToEqsL1FyKKHgRxQYN20M_GIqKESGjqx
"""

def solution(m, n, puddles):
    metrics = [[1]*m for _ in range(n)]
    for p in puddles:
        [x,y] = p
        metrics[y-1][x-1] = 0
        if (x-1) == 0:
            for i in range(y-1, n):
                metrics[i][x-1] = 0
        if (y-1) == 0:
            for i in range(x-1, m):
                metrics[y-1][i] = 0
    
    for i in range(1,n):
        for j in range(1,m):
            if metrics[i][j] != 0:
                metrics[i][j] = metrics[i-1][j] + metrics[i][j-1]
    answer = metrics[n-1][m-1] % 1000000007
    
    return answer

solution(4, 3, [[2, 2]])