# -*- coding: utf-8 -*-
"""단속_카메라.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XkeFAW6RyY9ejJqmdOkLJuIe9pdgKHV5
"""

def solution(routes):
    answer = 0
    routes.sort(key=lambda x: x[1]) 
    camera = -30001 

    for route in routes:
        if camera < route[0]:
            answer += 1
            camera = route[1]
    return answer