# -*- coding: utf-8 -*-
"""모음사전.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XkeFAW6RyY9ejJqmdOkLJuIe9pdgKHV5
"""

def solution(word):
    answer = 0
    arr = ['A', 'E', 'I', 'O', 'U']
    num = [781, 156, 31, 6, 1]
    for i in range(len(word)):
        answer += arr.index(word[i]) * num[i] + 1
    return answer

solution("AAAAE")