# -*- coding: utf-8 -*-
"""같은숫자는싫어.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11w2ly0jV8ftX7UOk_P1nfP35uNre6f-m
"""

def solution(s):
    answer = True
    arr = []   
  
    for i in s:
        if i == '(':  
            arr.append(i) 
        else: 
            if arr == []: 
                answer = False
                break
            else:
                arr.pop() 

    if arr != []: 
        answer = False

    return answer