# -*- coding: utf-8 -*-
"""폰캣몬.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11w2ly0jV8ftX7UOk_P1nfP35uNre6f-m
"""

def solution(nums):
    answer = len(nums)/2
    nums = set(nums)
    print(nums)

    if answer > len(nums):
        answer = len(nums)

    return answer    
solution([3,1,2,3])