# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ToEqsL1FyKKHgRxQYN20M_GIqKESGjqx
"""

def solution(numbers, target):
    lst = [0]
    for num in numbers:
        sub = []
        for num_ in lst:
            sub.append(num_ + num)
            sub.append(num_ - num)
        lst = sub
    return lst.count(target)
          
    return answer

print(solution([1, 1, 1, 1, 1],	3))
print(solution([4, 1, 2, 1], 4))